#!/usr/bin/env python3.6

import requests

url = "https://www.python.org/static/community_logos/python-logo-master-v3-TM.png"

res = requests.get(url)
with open('python_logo.png','wb') as myfile:
    myfile.write(res.content)
