#!/usr/bin/env python3.6

import json

new_data = {"e":5}

with open("sample.json","r+") as myfile:
    data = json.load(myfile)
    data.update(new_data)
    myfile.seek(0)
    json.dump(data,myfile)
