#!/usr/bin/env python3.6

import json

new_data = {"name":"waseem"}

with open('sample.json') as myfile:
    data = json.load(myfile)

data.update(new_data)

with open("sample.json","w") as myfile:
    json.dump(data,myfile)
