#!/usr/bin/env python3.6

import subprocess
import boto3

#mysqldump -h db@192.168.0.1 -u username -p password

username = 'username'
password = 'password'
database = 'database_url'
db_name = 'db@192.168.0.1'

with open('mybackup.sql,'w') as myfile:
        c = subprocess.Popen(['mysqldumb','-h', db_name, '-u', username, '-p',password],
        stdout=myfile, shell=True)

with open('backup.sql','w') as output:
    command = subprocess.Popen(['mysqldump','-u', username, '-p',password, database],
            stdout=output, shell=True)

s3 = boto3.client('s3')
with open('backup.sql', 'rb') as f:
    s3.upload_fileobj(f, 'bucket_name', 's3backup.sql')
