#!/usr/bin/env python3.6

import boto3
ec2 = boto3.client('ec2')

instance_id = 'i-061ad8a6780a1c399'

ec2.stop_instances(InstanceIds=[instance_id])
waiter = ec2.get_waiter('instance_stopped')
waiter.wait(InstanceIds=[instance_id])

ec2.modify_instance_attribute(InstanceId=instance_id, Attribute='instanceType', Value='t2.medium')

ec2.start_instances(InstanceIds=[instance_id])
