#!/usr/bin/env python3.6

import os

stage = os.getenv("STAGE","Development").upper()

output = f"we are running in {stage}"

if stage.startswith("PROD"):
    output = "DANGER !!! "+ output

print(output)
