#!/usr/bin/env python3.6

from argparse import ArgumentParser
import requests
import sys
import os

parser = ArgumentParser(description='Get the current weather information')
parser.add_argument('zip', help='zip or postal code to get the weather for')
parser.add_argument('--country',default='in',help="country the zip code belongs to, default is 'India/in'")

args = parser.parse_args()

api_key = os.getenv('OWM_API_KEY')

if not api_key:
    print("Error: No 'OWM_API_KEY' provided")
    sys.exit(1)

url = f"http://api.openweathermap.org/data/2.5/weather?zip={args.zip},{args.country}&appid={api_key}"

res = requests.get(url)

if res.status_code != 200:
    print(f"Error talking to weather provider: {res.status_code}")
    sys.exit(1)

print(res.json())
